apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aipx

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: oms
  app.kubernetes.io/component: order-management
  app.kubernetes.io/part-of: aipx
