apiVersion: v1
kind: Service
metadata:
  name: cognitive-service
  namespace: aipx
  labels:
    app: cognitive-service
spec:
  type: ClusterIP
  selector:
    app: cognitive-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
  - name: metrics
    port: 9093
    targetPort: 9093
