apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aipx

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - networkpolicy.yaml
  - resourcequota.yaml
  - limitrange.yaml

commonLabels:
  app.kubernetes.io/part-of: aipx
  app.kubernetes.io/managed-by: kustomize
