apiVersion: v1
kind: ServiceAccount
metadata:
  name: aipx-service-account
  namespace: aipx
  labels:
    app.kubernetes.io/part-of: aipx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aipx-role
  namespace: aipx
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aipx-rolebinding
  namespace: aipx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aipx-role
subjects:
- kind: ServiceAccount
  name: aipx-service-account
  namespace: aipx
