apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aipx

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: user-service
  app.kubernetes.io/component: user-management
  app.kubernetes.io/part-of: aipx
